# Macro file for example B4
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/run/numberOfThreads 4                      # run the application with 4 threads
#/control/cout/ignoreThreadsExcept 0
#
/run/initialize                             # initialises the geometry of the application
#
/control/loop run2.mac zpos 10 10 1          # loops the value of zpos in run2.mac from 0 to 10 in steps of 1
